### ISSUE TITLE
Download button doesn't work

### ISSUE THREAD

**Issue by Hugao** [SkeletonFramework/skeletonframework.github.io#1]
The download button of the page don't work, it gives a JavaScript exception.
![Firebug](http://i.imgur.com/Smsl2wk.png)

**Comment by benhinchley** [comment]
Are you downloading from the github releases page?

**Comment by benhinchley** [comment]
@Hugao it looks like the download button is not actually linked to anything yet

**Comment by Hugao** [comment]
@benhinchley Yup. You're using the href value from the, that only contains # and you are missing the brackets on offset ``$target.offset().top()-40``

**Comment by benhinchley** [comment]
Yep i'll fix that asap, thanks @Hugao for bringing this up

**Comment by benhinchley** [comment]
this has been fixed in cadc5bb298804037851aabb275be4752b93ed873

**Comment by Hugao** [comment]
@benhinchley  no problem :+1:
